.TH OOREXX-CONFIG 1 "02 July 2008" "Version 4.0.0"
.SH NAME
\fBoorexx-config\fP \- Open Object Rexx Configuration
.SH SYNTAX
.B rexx
.RI [--help|--cflags|--libs|--prefix|--version]
.SH DESCRIPTION
.I Open Object Rexx Configuration
is a script to query the parameters of the current rexx installation
.PP
For further information, read the README and the other
documentation files included in the Open Object Rexx distribution.
.SH OPTIONS
.TP
.B --help
show help.
.TP
.B --cflags
shows the pre-processor and compiler flags.
.TP
.B --libs
shows the library linking information.
.TP
.B --prefix
shows the ooRexx install prefix.
.TP
.B --version
shows version information.

.SH "SEE ALSO"
.BR rexx (1)

.SH LICENSE
Open Object Rexx is distributed under the terms of the Common Public
License v1.0 which accompanies this distribution.
http://www.oorexx.org/license.html

