.TH REXX 1 "March 2010" "Version 4.0.1"
.SH NAME
\fBrexx\fP \- Open Object Rexx Interpreter
.SH SYNTAX
.B rexx
.RI [-v]
.RI [filename
.RI |
.RI -e
.RI statements]
.RI [arguments]
.SH DESCRIPTION
.I Open Object Rexx
is an object-oriented scripting language based on and
compatible with Rexx that fully supports object-oriented
concepts. It provides open interfaces to many system
functions such as TCP/IP sockets, FTP for communications,
and C for programming.
You should report bugs at
http://sourceforge.net/tracker/?group_id=119701&atid=684730
.PP
For further information, read the README and the other
documentation files included in the Open Object Rexx distribution.

.SH OPTIONS
.TP
.B -v
display the build date of the product.
.TP
.B -e
Rexx program statements. These should be contained within double quotes.

.SH "SEE ALSO"
.BR rexxc (1)

.SH LICENSE
Open Object Rexx is distributed under the terms of the Common Public
License v1.0 which accompanies this distribution.
http://www.oorexx.org/license.html

