.TH REXX 1 "April 2021" "Version 5.0.0"
.SH NAME
\fBrexx\fP \- Open Object Rexx Interpreter
.SH SYNTAX
.BI "rexx " filename
.RI [ arguments ]
.PP
.B rexx
.RI "-e " "program_string " [ arguments ]
.PP
.BR "rexx " -v
.SH DESCRIPTION
.RI "Executes an " "Open Object Rexx " "(ooRexx) script"
.RI "with the given " "filename " "or from " program_string .
.PP
ooRexx is an object-oriented scripting language based on and
compatible with Rexx that fully supports object-oriented
concepts. It provides open interfaces to many system
functions such as TCP/IP sockets, FTP for communications,
and C for programming.
You should report bugs at
https://sourceforge.net/p/oorexx/bugs/
.PP
For further information, read the README and the other
documentation files included in the Open Object Rexx distribution.

.SH OPTIONS
.TP
.B -e
Rexx program string; should be contained within double quotes.
.TP
.B -v
displays ooRexx version, build date, and addressing mode.

.SH "SEE ALSO"
.BR rexxc (1)

.SH LICENSE
This program and the accompanying materials are made available under
the terms of the Common Public License v1.0 which accompanies this
distribution. A copy is also available at the following address:
https://www.oorexx.org/license.html
