.TH RXDELIPC 1 "02 July 2008" "Version 4.0.0"
.SH NAME
\fBoorexx-config\fP \- Open Object Rexx Shared Memory Clean
.SH SYNTAX
.B rxdelipc
.RI [-f|-h]
.SH DESCRIPTION
.I Open Object Rexx Shared Memory Clean
is a tool to lear the shared memory of the ooRexx interpreter. The
shared memory stores the environment, macro space and internal data.
It may be corrupted in case the rexx interpreter had to be killed
and the clean up failed to work.
.PP
Only use this tool in case the shared memory is corrupted in a
way such that ooRexx can not recover from it.
.PP
For further information, read the README and the other
documentation files included in the Open Object Rexx distribution.
.SH OPTIONS
.TP
.B -h
show help.
.TP
.B -f
force purging the shared memory.

.SH "SEE ALSO"
.BR rexx (1)

.SH LICENSE
Open Object Rexx for Linux is distributed under the terms of
the Common Public License v1.0 which accompanies this distribution.
http://www.oorexx.org/license.html

