.TH RXQUEUE 1 "March 2010" "Version 4.1.0"
.SH NAME
\fBrxqueue\fP \- Open Object Rexx Queue Filter
.SH SYNTAX
.B rxqueue
.RI [queuename]
.RI [/FIFO|/LIFO/CLEAR]
.SH DESCRIPTION
This program operates as a filter, placing the output of an operating system command onto an
Open Object Rexx queue.

.PP
The name of the queue to act upon is determined in the following order:

.TP
1.
.B queuename
specified on the command line
.TP
2.
The name of the queue specified by the environment variable
.B RXQUEUE
.TP
3.
The default queue name
.B SESSION

.SH OPTIONS
.TP
.B /FIFO
places lines onto the queue in first-in first out order. This is the default.
.TP
.B /LIFO
places lines onto the queue in last-in first out order.
.TP
.B /CLEAR
removes all lines from the queue.

.SH "SEE ALSO"
.BR rxsubcom (1)

.SH EXAMPLES
.TP
ls | rxqueue MYQ /LIFO
Place the output from the
.B ls
command onto the
.B MYQ
queue in last-in first-out order

.TP
export RXQUEUE=MYQ;rxqueue /CLEAR
Clear the contents of
.B MYQ

.SH LICENSE
Open Object Rexx is distributed under the terms of
the Common Public License v1.0 which accompanies this distribution.
http://www.oorexx.org/license.html
