.TH RXSUBCOM 1 "March 2010" "Version 4.2.0"
.SH NAME
\fBrxsubcom\fP \- Open Object Rexx Subcommand Administrator
.SH SYNTAX
.B rxsubcom
.RI REGISTER
.RI environment
.RI sharedLibrary
.RI function

.B rxsubcom
.RI QUERY
.RI sharedLibrary
.RI [function]

.B rxsubcom
.RI DROP
.RI sharedLibrary
.RI [function]

.B rxsubcom
.RI LOAD
.RI sharedLibrary
.RI [function]

.SH DESCRIPTION
The
.B rxsubcom
command registers, drops, and queries Rexx subcommand handlers. A Rexx program can use
.B rxsubcom
to register dynamic-link library subcommand handlers. Once the subcommand handler is registered,
the Rexx program can send commands to the subcommand handler with the Rexx ADDRESS instruction.

.SH "SEE ALSO"
.BR rxqueue (1)

.SH EXAMPLES
.TP
rxsubcom register mysub libmysub.so StartMySub
Registers the
.B mysub
environment in the
.B libmysub.so
shared library

.TP
rxsubcom drop libmysub.so
Drops the subcommand environment provided by the shared library
.B libmysub.so

.SH LICENSE
Open Object Rexx is distributed under the terms of
the Common Public License v1.0 which accompanies this distribution.
http://www.oorexx.org/license.html
