#!/bin/sh   -x 

VER=4
REL=0
MOD=1

echo $SCRIPT_NAME: linking files

echo $SCRIPT_NAME: linking libraries to /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexx                 /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexx.$VER.$REL.$MOD.dylib     /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexx.$VER.dylib         /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexx.a               /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexx.dylib           /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexx.la              /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxapi              /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxapi.$VER.$REL.$MOD.dylib  /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxapi.$VER.dylib      /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxapi.a            /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxapi.dylib        /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxapi.la           /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxutil             /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxutil.$VER.$REL.$MOD.dylib /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxutil.$VER.dylib     /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxutil.a           /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxutil.dylib       /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librexxutil.la          /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxmath               /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxmath.$VER.$REL.$MOD.dylib   /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxmath.$VER.dylib       /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxmath.a             /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxmath.dylib         /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxmath.la            /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxregexp             /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxregexp.$VER.$REL.$MOD.dylib /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxregexp.$VER.dylib     /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxregexp.a           /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxregexp.dylib       /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxregexp.la          /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxsock               /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxsock.$VER.$REL.$MOD.dylib   /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxsock.$VER.dylib       /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxsock.a             /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxsock.dylib         /usr/lib
ln -sf /opt/ooRexx/lib/ooRexx/librxsock.la            /usr/lib

echo $SCRIPT_NAME: linking programs to /usr/bin
ln -sf /opt/ooRexx/bin/oorexx-config /usr/bin
ln -sf /opt/ooRexx/bin/rexx          /usr/bin
ln -sf /opt/ooRexx/bin/rexx.cat      /usr/bin
ln -sf /opt/ooRexx/bin/rexx.img      /usr/bin
ln -sf /opt/ooRexx/bin/rexxc         /usr/bin
ln -sf /opt/ooRexx/bin/rexximage     /usr/bin
ln -sf /opt/ooRexx/bin/rxapi         /usr/bin
ln -sf /opt/ooRexx/bin/rxapid        /usr/bin
ln -sf /opt/ooRexx/bin/rxftp.cls     /usr/bin
ln -sf /opt/ooRexx/bin/rxqueue       /usr/bin
ln -sf /opt/ooRexx/bin/rxregexp.cls  /usr/bin
ln -sf /opt/ooRexx/bin/rxsubcom      /usr/bin
ln -sf /opt/ooRexx/bin/socket.cls    /usr/bin

echo $SCRIPT_NAME: linking man pages to /usr/share/man/man1
ln -sf /opt/ooRexx/share/man/man1/oorexx-config.1 /usr/share/man/man1
ln -sf /opt/ooRexx/share/man/man1/rexx.1          /usr/share/man/man1
ln -sf /opt/ooRexx/share/man/man1/rexxc.1         /usr/share/man/man1
ln -sf /opt/ooRexx/share/man/man1/rxmigrate.1     /usr/share/man/man1
ln -sf /opt/ooRexx/share/man/man1/rxqueue.1       /usr/share/man/man1
ln -sf /opt/ooRexx/share/man/man1/rxsubcom.1      /usr/share/man/man1

echo $SCRIPT_NAME: linking headers to /usr/include
ln -sf /opt/ooRexx/include/oorexxapi.h        /usr/include
ln -sf /opt/ooRexx/include/oorexxerrors.h     /usr/include
ln -sf /opt/ooRexx/include/rexx.h             /usr/include
ln -sf /opt/ooRexx/include/rexxapidefs.h      /usr/include
ln -sf /opt/ooRexx/include/rexxapitypes.h     /usr/include
ln -sf /opt/ooRexx/include/rexxplatformapis.h /usr/include
ln -sf /opt/ooRexx/include/rexxplatformdefs.h /usr/include

echo $SCRIPT_NAME:  linking Launch Daemon to /Library/LaunchDaemons
ln -sf /opt/ooRexx/bin/org.rexxla.oorexx.rxapid.plist /Library/LaunchDaemons

echo $SCRIPT_NAME:  stop/start rxapi Daemon
launchctl unload -w /Library/LaunchDaemons/org.rexxla.oorexx.rxapid.plist
launchctl load -w /Library/LaunchDaemons/org.rexxla.oorexx.rxapid.plist

echo $SCRIPT_NAME: linking complete
