#!/bin/sh
echo $SCRIPT_NAME: Removing prior version of ooRexx.

echo $SCRIPT_NAME: Removing links from /usr/lib.
rm -f /usr/lib/librexx.*
rm -f /usr/lib/librexxapi.*
rm -f /usr/lib/librexxutil.*
rm -f /usr/lib/librxmath.*
rm -f /usr/lib/librxregexp.*
rm -f /usr/lib/librxsock.*

echo $SCRIPT_NAME: Removing libraries from /opt/ooRexx/lib/ooRexx.
rm -f /opt/ooRexx/lib/ooRexx/librexx.*
rm -r /opt/ooRexx/lib/ooRexx/librexxapi.*
rm -f /opt/ooRexx/lib/ooRexx/librexxutil.*
rm -f /opt/ooRexx/lib/ooRexx/librxmath.*
rm -f /opt/ooRexx/lib/ooRexx/librxregexp.*
rm -f /opt/ooRexx/lib/ooRexx/librxsock.*

echo $SCRIPT_NAME: Removing links from /usr/bin.
rm -f /usr/bin/oorexx-config
rm -f /usr/bin/rexx
rm -f /usr/bin/rexx.cat
rm -f /usr/bin/rexx.img
rm -f /usr/bin/rexxc
rm -f /usr/bin/rxdelipc
rm -f /usr/bin/rxftp.cls
rm -f /usr/bin/rxmigrate
rm -f /usr/bin/rxqueue
rm -f /usr/bin/rxregexp.cls
rm -f /usr/bin/rxsubcom

echo $SCRIPT_NAME: Removing programs from /opt/ooRexx/bin.
rm -f /opt/ooRexx/bin/oorexx-config
rm -f /opt/ooRexx/bin/org.rexxla.oorexx.rxapid.plist
rm -f /opt/ooRexx/bin/rexx
rm -f /opt/ooRexx/bin/rexx.cat
rm -f /opt/ooRexx/bin/rexx.img
rm -f /opt/ooRexx/bin/rexxc
rm -f /opt/ooRexx/bin/rxapi
rm -f /opt/ooRexx/bin/rxapid
rm -f /opt/ooRexx/bin/rxdelipc
rm -f /opt/ooRexx/bin/rxftp.cls
rm -f /opt/ooRexx/bin/rxmigrate
rm -f /opt/ooRexx/bin/rxqueue
rm -f /opt/ooRexx/bin/rxregexp.cls
rm -f /opt/ooRexx/bin/rxsubcom

echo $SCRIPT_NAME: Removing man pages from /opt/ooRexx/share/man/man1.
rm -f /opt/ooRexx/share/man/man1/oorexx-config.1
rm -f /opt/ooRexx/share/man/man1/rexx.1
rm -f /opt/ooRexx/share/man/man1/rexxc.1
rm -f /opt/ooRexx/share/man/man1/rxqueue.1
rm -f /opt/ooRexx/share/man/man1/rxsubcom.1

echo $SCRIPT_NAME: Removing rexx examples from /opt/ooRexx/share/ooRexx.
rm -f /opt/ooRexx/share/ooRexx/ccreply.rex
rm -f /opt/ooRexx/share/ooRexx/complex.rex
rm -f /opt/ooRexx/share/ooRexx/factor.rex
rm -f /opt/ooRexx/share/ooRexx/greply.rex
rm -f /opt/ooRexx/share/ooRexx/guess.rex
rm -f /opt/ooRexx/share/ooRexx/ktguard.rex
rm -f /opt/ooRexx/share/ooRexx/makestring.rex
rm -f /opt/ooRexx/share/ooRexx/month.rex
rm -f /opt/ooRexx/share/ooRexx/philfork.rex
rm -f /opt/ooRexx/share/ooRexx/pipe.rex
rm -f /opt/ooRexx/share/ooRexx/properties.rex
rm -f /opt/ooRexx/share/ooRexx/qdate.rex
rm -f /opt/ooRexx/share/ooRexx/qtime.rex
rm -f /opt/ooRexx/share/ooRexx/readme
rm -f /opt/ooRexx/share/ooRexx/rexx.csh
rm -f /opt/ooRexx/share/ooRexx/rexx.sh
rm -f /opt/ooRexx/share/ooRexx/rexxcps.rex
rm -f /opt/ooRexx/share/ooRexx/rexxtry.rex
rm -f /opt/ooRexx/share/ooRexx/scclient.rex
rm -f /opt/ooRexx/share/ooRexx/scserver.rex
rm -f /opt/ooRexx/share/ooRexx/semcls.rex
rm -f /opt/ooRexx/share/ooRexx/sfclient.rex
rm -f /opt/ooRexx/share/ooRexx/sfserver.rex
rm -f /opt/ooRexx/share/ooRexx/stack.rex
rm -f /opt/ooRexx/share/ooRexx/usecomp.rex
rm -f /opt/ooRexx/share/ooRexx/usepipe.rex

echo $SCRIPT_NAME: Shutting down rxapi daemon
launchctl unload -w /Library/LaunchDaemons/org.rexxla.oorexx.rxapid.plist

echo $SCRIPT_NAME: Removing rexx LaunchDeamon 
rm -f /Library/LaunchDeamons/org.rexxla.oorexx.rxapid.plist

echo $SCRIPT_NAME: Removal of prior version of ooRexx complete.
