/*----------------------------------------------------------------------------*/
/*                                                                            */
/* Copyright (c) 2011-2014 Rexx Language Association. All rights reserved.    */
/*                                                                            */
/* This program and the accompanying materials are made available under       */
/* the terms of the Common Public License v1.0 which accompanies this         */
/* distribution. A copy is also available at the following address:           */
/* http://www.oorexx.org/license.html                                         */
/*                                                                            */
/* Redistribution and use in source and binary forms, with or                 */
/* without modification, are permitted provided that the following            */
/* conditions are met:                                                        */
/*                                                                            */
/* Redistributions of source code must retain the above copyright             */
/* notice, this list of conditions and the following disclaimer.              */
/* Redistributions in binary form must reproduce the above copyright          */
/* notice, this list of conditions and the following disclaimer in            */
/* the documentation and/or other materials provided with the distribution.   */
/*                                                                            */
/* Neither the name of Rexx Language Association nor the names                */
/* of its contributors may be used to endorse or promote products             */
/* derived from this software without specific prior written permission.      */
/*                                                                            */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        */
/* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          */
/* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS          */
/* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT   */
/* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,      */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED   */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,        */
/* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY     */
/* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING    */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               */
/*                                                                            */
/*----------------------------------------------------------------------------*/

"",
"LBUTTON",
"RBUTTON",
"CANCEL",
"MBUTTON",
"XBUTTON1",
"XBUTTON2",
"",
"BACK",
"TAB",
"",
"",
"CLEAR",
"RETURN",
"",
"",
"SHIFT",
"CONTROL",
"MENU",
"PAUSE",
"CAPITAL",
"KANA",
"",
"JUNJA",
"FINAL",
"HANJA",
"",
"ESCAPE",
"CONVERT",
"NONCONVERT",
"ACCEPT",
"MODECHANGE",
"SPACE",
"PRIOR",
"NEXT",
"END",
"HOME",
"LEFT",
"UP",
"RIGHT",
"DOWN",
"SELECT",
"PRINT",
"EXECUTE",
"SNAPSHOT",
"INSERT",
"DELETE",
"HELP",
"0",
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"",
"",
"",
"",
"",
"",
"",
"A",
"B",
"C",
"D",
"E",
"F",
"G",
"H",
"I",
"J",
"K",
"L",
"M",
"N",
"O",
"P",
"Q",
"R",
"S",
"T",
"U",
"V",
"W",
"X",
"Y",
"Z",
"LWIN",
"RWIN",
"APPS",
"",
"SLEEP",
"NUMPAD0",
"NUMPAD1",
"NUMPAD2",
"NUMPAD3",
"NUMPAD4",
"NUMPAD5",
"NUMPAD6",
"NUMPAD7",
"NUMPAD8",
"NUMPAD9",
"MULTIPLY",
"ADD",
"SEPARATOR",
"SUBTRACT",
"DECIMAL",
"DIVIDE",
"F1",
"F2",
"F3",
"F4",
"F5",
"F6",
"F7",
"F8",
"F9",
"F10",
"F11",
"F12",
"F13",
"F14",
"F15",
"F16",
"F17",
"F18",
"F19",
"F20",
"F21",
"F22",
"F23",
"F24",
"",
"",
"",
"",
"",
"",
"",
"",
"NUMLOCK",
"SCROLL",
"OEM_NEC_EQUAL",
"OEM_FJ_MASSHOU",
"OEM_FJ_TOUROKU",
"OEM_FJ_LOYA",
"OEM_FJ_ROYA",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"LSHIFT",
"RSHIFT",
"LCONTROL",
"RCONTROL",
"LMENU",
"RMENU",
"BROWSER_BACK",
"BROWSER_FORWARD",
"BROWSER_REFRESH",
"BROWSER_STOP",
"BROWSER_SEARCH",
"BROWSER_FAVORITES",
"BROWSER_HOME",
"VOLUME_MUTE",
"VOLUME_DOWN",
"VOLUME_UP",
"MEDIA_NEXT_TRACK",
"MEDIA_PREV_TRACK",
"MEDIA_STOP",
"MEDIA_PLAY_PAUSE",
"LAUNCH_MAIL",
"LAUNCH_MEDIA_SELECT",
"LAUNCH_APP1",
"LAUNCH_APP2",
"",
"",
"OEM_1",
"OEM_PLUS",
"OEM_COMMA",
"OEM_MINUS",
"OEM_PERIOD",
"OEM_2",
"OEM_3",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"OEM_4",
"OEM_5",
"OEM_6",
"OEM_7",
"OEM_8",
"",
"OEM_AX",
"OEM_102",
"ICO_HELP",
"ICO_00",
"PROCESSKEY",
"ICO_CLEAR",
"PACKET",
"",
"OEM_RESET",
"OEM_JUMP",
"OEM_PA1",
"OEM_PA2",
"OEM_PA3",
"OEM_WSCTRL",
"OEM_CUSEL",
"OEM_ATTN",
"OEM_FINISH",
"OEM_COPY",
"OEM_AUTO",
"OEM_ENLW",
"OEM_BACKTAB",
"ATTN",
"CRSEL",
"EXSEL",
"EREOF",
"PLAY",
"ZOOM",
"NONAME",
"PA1",
"OEM_CLEAR",
""
