#!/bin/sh
#/*----------------------------------------------------------------------------*/
#/*                                                                            */
#/* Copyright (c) 2007-2009 Rexx Language Association. All rights reserved.    */
#/*                                                                            */
#/* This program and the accompanying materials are made available under       */
#/* the terms of the Common Public License v1.0 which accompanies this         */
#/* distribution. A copy is also available at the following address:           */
#/* http://www.oorexx.org/license.html                                         */
#/*                                                                            */
#/* Redistribution and use in source and binary forms, with or                 */
#/* without modification, are permitted provided that the following            */
#/* conditions are met:                                                        */
#/*                                                                            */
#/* Redistributions of source code must retain the above copyright             */
#/* notice, this list of conditions and the following disclaimer.              */
#/* Redistributions in binary form must reproduce the above copyright          */
#/* notice, this list of conditions and the following disclaimer in            */
#/* the documentation and/or other materials provided with the distribution.   */
#/*                                                                            */
#/* Neither the name of Rexx Language Association nor the names                */
#/* of its contributors may be used to endorse or promote products             */
#/* derived from this software without specific prior written permission.      */
#/*                                                                            */
#/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        */
#/* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          */
#/* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS          */
#/* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT   */
#/* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,      */
#/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED   */
#/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,        */
#/* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY     */
#/* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING    */
#/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         */
#/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               */
#/*                                                                            */
#/*----------------------------------------------------------------------------*/

rm -f /usr/bin/rexx
rm -f /usr/bin/rexxc
rm -f /usr/bin/rxqueue
rm -f /usr/bin/rxsubcom
rm -f /usr/bin/rxdelipc
rm -f /usr/bin/rexx.img
rm -f /usr/bin/rexx.cat
rm -f /usr/bin/rxregexp.cls
rm -f /usr/bin/rxftp.cls
rm -f /usr/bin/socket.cls
rm -f /usr/bin/streamsocket.cls
rm -f /usr/bin/mime.cls
rm -f /usr/bin/smtp.cls
rm -f /usr/bin/oorexx-config

rm -f /usr/lib/librexx.*
rm -f /usr/lib/librexxapi.*
rm -f /usr/lib/librxsock.*
rm -f /usr/lib/librxmath.*
rm -f /usr/lib/librxregexp.*
rm -f /usr/lib/librexxutil.*

rm -f /usr/share/man/man1/oorexx-config.1
rm -f /usr/share/man/man1/rexx.1
rm -f /usr/share/man/man1/rexxc.1
rm -f /usr/share/man/man1/rxsubcom.1
rm -f /usr/share/man/man1/rxqueue.1
rm -f /usr/share/man/man1/rxdelipc.1  # remove from previous ooRexx versions
rm -f /usr/include/rexx.h
rm -f /usr/include/rexxapidefs.h
rm -f /usr/include/rexxapitypes.h
rm -f /usr/include/rexxplatformapis.h
rm -f /usr/include/rexxplatformdefs.h
rm -f /usr/include/oorexxapi.h
rm -f /usr/include/oorexxerrors.h
rm -f /usr/bin/rexxtry.rex
rm -rf /usr/share/ooRexx

if [ -d /etc/rc.d/init.d ]; then
   # Red Hat
   /etc/rc.d/init.d/rxapid stop
   rm /etc/rc.d/rc3.d/S89rxapid
   rm /etc/rc.d/rc5.d/S89rxapid
   rm /etc/rc.d/init.d/rxapid
elif [ -d /etc/init.d ]; then
   # Debian
   if [ -e /etc/init.d/rxapid ]; then
      /etc/init.d/rxapid stop
   fi
   rm -f /etc/init.d/rc3.d/S89rxapid
   rm -f /etc/init.d/rc5.d/S89rxapid
   rm -f /etc/init.d/rxapid
else
   # This does work for SuSE, but I think the Debian above would also work
   /etc/rc.d/rxapid stop
   rm /etc/rc.d/rc3.d/S89rxapid
   rm /etc/rc.d/rc5.d/S89rxapid
   rm /etc/rc.d/rxapid
fi
