

/*----------------------------------------------------------------------------*/
/*                                                                            */
/* Copyright (c) 1995, 2004 IBM Corporation. All rights reserved.             */
/* Copyright (c) 2005-2006 Rexx Language Association. All rights reserved.    */
/*                                                                            */
/* This program and the accompanying materials are made available under       */
/* the terms of the Common Public License v1.0 which accompanies this         */
/* distribution. A copy is also available at the following address:           */
/* http://www.ibm.com/developerworks/oss/CPLv1.0.htm                          */
/*                                                                            */
/* Redistribution and use in source and binary forms, with or                 */
/* without modification, are permitted provided that the following            */
/* conditions are met:                                                        */
/*                                                                            */
/* Redistributions of source code must retain the above copyright             */
/* notice, this list of conditions and the following disclaimer.              */
/* Redistributions in binary form must reproduce the above copyright          */
/* notice, this list of conditions and the following disclaimer in            */
/* the documentation and/or other materials provided with the distribution.   */
/*                                                                            */
/* Neither the name of Rexx Language Association nor the names                */
/* of its contributors may be used to endorse or promote products             */
/* derived from this software without specific prior written permission.      */
/*                                                                            */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        */
/* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          */
/* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS          */
/* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT   */
/* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,      */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED   */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,        */
/* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY     */
/* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING    */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               */
/*                                                                            */
/*----------------------------------------------------------------------------*/
/******************************************************************************/
/* REXX  Support                                                              */
/*                                                                            */
/* Rexx primitive class id codes                                              */
/*                                                                            */
/*        -- DO NOT CHANGE THIS FILE, ALL CHANGES WILL BE LOST! --            */
/*                  -- FILE WAS GENERATED BY ClassTypeIds.xsl --              */
/******************************************************************************/

#ifndef ClassTypeCodes_Included
#define ClassTypeCodes_Included

typedef enum
{
    T_First_Primitive_Class = 0,
    T_First_Exported_Class = 0,

    T_Object = 0,
    T_ObjectClass = 1,
    T_Class = 2,
    T_ClassClass = 3,
    T_Array = 4,
    T_ArrayClass = 5,
    T_Directory = 6,
    T_DirectoryClass = 7,
    T_Integer = 8,
    T_IntegerClass = 9,
    T_List = 10,
    T_ListClass = 11,
    T_Message = 12,
    T_MessageClass = 13,
    T_Method = 14,
    T_MethodClass = 15,
    T_NumberString = 16,
    T_NumberStringClass = 17,
    T_Queue = 18,
    T_QueueClass = 19,
    T_Stem = 20,
    T_StemClass = 21,
    T_String = 22,
    T_StringClass = 23,
    T_Supplier = 24,
    T_SupplierClass = 25,
    T_Table = 26,
    T_TableClass = 27,
    T_Relation = 28,
    T_RelationClass = 29,
    T_MutableBuffer = 30,
    T_MutableBufferClass = 31,
    T_Pointer = 32,
    T_PointerClass = 33,
    T_Buffer = 34,
    T_BufferClass = 35,
    T_WeakReference = 36,
    T_WeakReferenceClass = 37,

    T_Last_Exported_Class = 37,
    
    T_First_Internal_Class = 38,

    T_NilObject = 38,
    T_Behaviour = 39,
    T_RexxSource = 40,
    T_RexxCode = 41,
    T_NativeCode = 42,
    T_CPPCode = 43,
    T_AttributeGetterCode = 44,
    T_AttributeSetterCode = 45,
    T_ConstantGetterCode = 46,
    T_AbstractCode = 47,
    T_HashTable = 48,
    T_ListTable = 49,
    T_SmartBuffer = 50,
    T_Variable = 51,
    T_VariableDictionary = 52,
    T_VariableTerm = 53,
    T_CompoundVariableTerm = 54,
    T_StemVariableTerm = 55,
    T_DotVariableTerm = 56,
    T_IndirectVariableTerm = 57,
    T_FunctionCallTerm = 58,
    T_MessageSendTerm = 59,
    T_UnaryOperatorTerm = 60,
    T_BinaryOperatorTerm = 61,
    T_LogicalTerm = 62,
    T_Instruction = 63,
    T_AddressInstruction = 64,
    T_AssignmentInstruction = 65,
    T_CallInstruction = 66,
    T_CommandInstruction = 67,
    T_DoInstruction = 68,
    T_DropInstruction = 69,
    T_ElseInstruction = 70,
    T_EndInstruction = 71,
    T_EndIfInstruction = 72,
    T_ExitInstruction = 73,
    T_ExposeInstruction = 74,
    T_ForwardInstruction = 75,
    T_GuardInstruction = 76,
    T_IfInstruction = 77,
    T_InterpretInstruction = 78,
    T_LabelInstruction = 79,
    T_LeaveInstruction = 80,
    T_MessageInstruction = 81,
    T_NopInstruction = 82,
    T_NumericInstruction = 83,
    T_OptionsInstruction = 84,
    T_OtherwiseInstruction = 85,
    T_ParseInstruction = 86,
    T_ProcedureInstruction = 87,
    T_QueueInstruction = 88,
    T_RaiseInstruction = 89,
    T_ReplyInstruction = 90,
    T_ReturnInstruction = 91,
    T_SayInstruction = 92,
    T_SelectInstruction = 93,
    T_SignalInstruction = 94,
    T_ThenInstruction = 95,
    T_TraceInstruction = 96,
    T_UseInstruction = 97,
    T_CompoundElement = 98,
    T_ParseTrigger = 99,

    T_Last_Internal_Class = 99,
    
    T_First_Transient_Class = 100,

    T_Memory = 100,
    T_InternalStack = 101,
    T_Stack = 102,
    T_Activity = 103,
    T_Activation = 104,
    T_NativeActivation = 105,
    T_ActivationFrameBuffer = 106,
    T_Envelope = 107,
    T_Clause = 108,
    T_Token = 109,
    T_DoBlock = 110,

    T_Last_Transient_Class = 110,
    T_Last_Primitive_Class = 110,
    T_Last_Class_Type = 110,
    
} ClassTypeCode;

/* -------------------------------------------------------------------------- */
/* --            ==================================================        -- */
/* --            DO NOT CHANGE THIS FILE, ALL CHANGES WILL BE LOST!        -- */
/* --            ==================================================        -- */
/* -------------------------------------------------------------------------- */
#endif

